---
- name: Descargar archivo
  get_url:
      url: http://idefix.dit.upm.es/download/cdps/pfinal/pfinal.tgz
      dest: /home/upm/pfinal.tgz
  tags: config_sce

- name: Descomprimir archivo
  unarchive:
      src: /home/upm/pfinal.tgz
      dest: /home/upm
      remote_src: yes
  become: yes
  become_user: root
  tags: config_sce

- name: Crear directorio clientes
  file:
      path: /home/upm/clients
      state: directory
      mode: 0755
  tags: config_sce

- name: Cambiar el nombre a la carpeta
  command: cp -r /home/upm/pfinal/. /home/upm/clients/.
  tags: config_sce

- name: Cambia el archivo xml para montarlo
  copy: src=/etc/ansible/roles/start_scenary/files/clients/clientes.xml dest=/home/upm/clients/ owner=root group=root mode=644
  tags: config_sce

- name: Cambia el archivo de configuracion de ips
  copy: src=/etc/ansible/roles/start_scenary/files/clients/hosts dest=/home/upm/clients/conf/ owner=root group=root mode=644
  tags: config_sce

- name: Crear el escenario
  command: vnx -f /home/upm/clients/clientes.xml --create
  become: yes
  become_user: root
  tags: config_sce

- name: Crear directorio CPD1
  file:
      path: /home/upm/CPD1
      state: directory
      mode: 0755
  tags: config_sce

- name: Cambiar el nombre a la carpeta
  command: cp -r /home/upm/pfinal/. /home/upm/CPD1/.
  tags: config_sce

- name: Cambia el archivo xml para montarlo
  copy: src=/etc/ansible/roles/start_scenary/files/CPD1/cpd1.xml dest=/home/upm/CPD1/ owner=root group=root mode=644
  tags: config_sce

- name: Cambia el archivo de configuracion de ips
  copy: src=/etc/ansible/roles/start_scenary/files/CPD1/hosts dest=/home/upm/CPD1/conf/ owner=root group=root mode=644
  tags: config_sce

- name: Arrancar el escenario
  command: /home/upm/CPD1/bin/prepare-pfinal-vm
  become: yes
  become_user: root
  tags: config_sce

- name: Crear el escenario
  command: vnx -f /home/upm/CPD1/cpd1.xml --create
  become: yes
  become_user: root
  tags: config_sce

- name: Crear directorio CPD2
  file:
      path: /home/upm/CPD2
      state: directory
      mode: 0755
  tags: config_sce

- name: Cambiar el nombre a la carpeta
  command: cp -r /home/upm/pfinal/. /home/upm/CPD2/.
  tags: config_sce

- name: Cambia el archivo xml para montarlo
  copy: src=/etc/ansible/roles/start_scenary/files/CPD2/cpd2.xml dest=/home/upm/CPD2/ owner=root group=root mode=644
  tags: config_sce

- name: Cambia el archivo de configuracion de ips
  copy: src=/etc/ansible/roles/start_scenary/files/CPD2/hosts dest=/home/upm/CPD2/conf/ owner=root group=root mode=644
  tags: config_sce

- name: Arrancar el escenario
  command: /home/upm/CPD2/bin/prepare-pfinal-vm
  become: yes
  become_user: root
  tags: config_sce

- name: Crear el escenario
  command: vnx -f /home/upm/CPD2/cpd2.xml --create
  become: yes
  become_user: root
  tags: config_sce
